#pragma once

#include "AnimationQuery.h"
#include "Buffer.h"
#include "Camera.h"
#include "EmittingQueue.h"
#include "Hit.h"
#include "Image.h"
#include "LightQueue.h"
#include "Material.h"
#include "MaterialLibrary.h"
#include "Object.h"
#include "Photon.h"
#include "RandomGenerator.h"
#include "Volume.h"
#include "WorkQueue.h"

#include <atomic>
#include <exception>
#include <memory>
#include <thread>
#include <vector>

/*

Pipeline: Photons <-> Hits -> Final hits -> Write

Photons:
* Emitted / bounced photons to cast against the scene
* Generated by lights and emissive volumes at the beginning of a frame
* Generated at bounce sites depending on material properties and number of bounces allowed

Hits:
* Results of photon casts from the previous queue
* Depending on material properties and remaining bounces, will emit more photons to be calculated
* If visible to the camera (normal facing camera, no objects between hit and camera), added to the final hits queue

Final hits:
* Scanned by "pixel sensors" to be written to final image

If photons are available, process those
Else if hits are available, process those
Else if final hits are available, scan those into the image buffer
Else, sleep

*/

class Worker
{
public:
    Worker(size_t index, size_t fetchSize);

    void start();
    void suspend();
    void resume();
    void stop();
    void exec();
    std::exception_ptr exception();

    void setBounceThreshold(size_t bounceThreshold);

    std::shared_ptr<Camera> camera;
    std::vector<std::shared_ptr<Object>> objects;
    std::shared_ptr<LightQueue> lightQueue;
    std::shared_ptr<WorkQueue<Photon>> photonQueue;
    std::shared_ptr<WorkQueue<PhotonHit>> hitQueue;
    std::shared_ptr<WorkQueue<PhotonHit>> finalHitQueue;
    // EmittingQueue holds bounce-hits awaiting daughter spawn. processPhotons
    // pushes here in parallel with hitQueue; processEmissions pulls back with
    // back-pressure gated on photonQueue free space (no spawn if there isn't
    // room for N daughters). Decouples raycasting from daughter generation and
    // bounds the steady-state PhotonQueue occupancy.
    std::shared_ptr<EmittingQueue> emittingQueue;
    std::shared_ptr<MaterialLibrary> materialLibrary;
    std::shared_ptr<Buffer> buffer;
    std::shared_ptr<Image> image;
    // Continuous-time transform oracle (vision doc pillar 1). Default initialization is
    // a StaticAnimationQuery — every transformAt() call returns the scene-load transform
    // regardless of time. Workers currently read object positions through the existing
    // Object::position() path; the animation query is plumbed for future use without
    // requiring a Worker API change.
    std::shared_ptr<AnimationQuery> animationQuery;

    size_t emitDuration = 0;
    size_t photonDuration = 0;
    size_t hitDuration = 0;
    size_t writeDuration = 0;

    size_t emitProcessed = 0;
    size_t photonsProcessed = 0;
    size_t hitsProcessed = 0;
    size_t finalHitsProcessed = 0;

private:
    bool processLights();
    bool processPhotons();
    bool processEmissions();
    bool processHits();
    bool processFinalHits();

    size_t m_index = 0;
    size_t m_fetchSize = 0;

    size_t m_bounceThreshold = 1;

    std::thread m_thread;

    std::atomic_bool m_running;
    std::atomic_bool m_suspend;

    RandomGenerator m_generator;

    std::vector<Hit> m_castBuffer;
    std::vector<PhotonHit> m_hitBuffer;
    std::vector<PhotonHit> m_volumeHitBuffer;

    std::exception_ptr m_exception;
};

// Diagnostic counters for the delta-material cone gate in processFinalHits. Reset between
// frames; queried after the render completes. Will be removed once the cone-budget tuning
// settles.
namespace WorkerDebug
{
size_t deltaHitsTotal();
size_t deltaHitsAccepted();
size_t deltaHitsRejectedBackface();
size_t deltaHitsRejectedConeOffset();
void resetDeltaHitCounters();

// Drop counters: number of pipeline items discarded because a destination
// WorkQueue was full. Queried after the render drains. Must be zero once
// claim-output-first back-pressure is in place.
size_t droppedEmitting();
size_t droppedRequeue();
size_t droppedHit();
size_t droppedFinal();
size_t droppedTotal();
void resetDropCounters();
}
