#pragma once

#include "AnimationQuery.h"
#include "Buffer.h"
#include "DensityGrid.h"
#include "Camera.h"
#include "Emitter.h"
#include "EmitterQueue.h"
#include "Hit.h"
#include "Image.h"
#include "LightQueue.h"
#include "Material.h"
#include "MaterialLibrary.h"
#include "Object.h"
#include "Photon.h"
#include "RandomGenerator.h"
#include "Volume.h"
#include "WorkQueue.h"

#include <atomic>
#include <exception>
#include <memory>
#include <thread>
#include <vector>

/*

Pipeline: Photons <-> Hits -> Final hits -> Write

Photons:
* Emitted / bounced photons to cast against the scene
* Generated by lights and emissive volumes at the beginning of a frame
* Generated at bounce sites depending on material properties and number of bounces allowed

Hits:
* Results of photon casts from the previous queue
* Depending on material properties and remaining bounces, will emit more photons to be calculated
* If visible to the camera (normal facing camera, no objects between hit and camera), added to the final hits queue

Final hits:
* Scanned by "pixel sensors" to be written to final image

If photons are available, process those
Else if hits are available, process those
Else if final hits are available, scan those into the image buffer
Else, sleep

*/

class Worker
{
public:
    Worker(size_t index, size_t fetchSize);

    void start();
    void suspend();
    void resume();
    void stop();
    void exec();
    std::exception_ptr exception();

    void setBounceThreshold(size_t bounceThreshold);

    // Single-photon DECAY termination cutoff, as an ABSOLUTE magnitude floor in
    // photon-magnitude (flux / light-count) units. A photon is terminated (the
    // random walk stops) once its current magnitude (max colour channel) falls
    // below terminationThreshold. The bounce cap is the hard depth bound.
    void setTerminationThreshold(double terminationThreshold);

    // Russian-roulette configuration (unbiased path termination). When `enabled`
    // is false the worker behaves exactly as the pre-RR pipeline. See
    // RenderSettings for the meaning of each field; they are copied in verbatim
    // by the Renderer before the worker starts.
    struct RussianRouletteConfig
    {
        bool enabled = false;
        size_t minBounces = 1;
        float minProbability = 0.05f;
        float referenceEnergy = 1.0f;
    };
    void setRussianRoulette(const RussianRouletteConfig& config);

    // Configurable daughter fan-out. `countOverride` (when > 0) forces an exact
    // count; otherwise the material's native daughterPhotonCount() is multiplied
    // by `scale` (rounded, min 1). Default (override 0, scale 1) is a no-op.
    void setDaughterCount(size_t countOverride, double scale);

    // Storage pivot M2: photons-per-light N used by the direct splat to normalize
    // each contribution by 1/N (the single count divide the gather applied at
    // lookup). Must be set before the worker starts; default 0 disables the splat.
    void setPhotonsPerLight(double photonsPerLight);

    // Firefly fix: world-space minimum splat-footprint radius. The direct camera
    // splat normalizes each photon by its pixel footprint area (pi * r^2) where
    // r = cameraDistance * tan(pixelHalfAngle). When an indirect photon lands on
    // geometry very close to the camera, r collapses toward zero and 1/(pi r^2)
    // explodes, spiking a single pixel to white (a firefly). Flooring r at this
    // minimum bounds the weight without discarding energy: a too-concentrated
    // splat is spread over the minimum footprint instead. The floor is derived
    // from the scene-depth pixel footprint (the same length that sizes the
    // density grid), so it scales with scene and camera geometry rather than
    // being an arbitrary constant. 0 disables the floor (legacy behavior).
    void setMinSplatRadius(double minSplatRadius);

    // Optional extreme-firefly guard: a generous upper bound on the luminance a
    // single camera splat may add to a pixel. The minimum-radius floor only
    // bounds the geometric 1/(pi r^2) blowup; this clamp also catches fireflies
    // whose energy comes from a degenerate transport path (normal footprint,
    // photon-count-invariant). A splat whose luminance exceeds the clamp is
    // scaled down to it, preserving hue. <= 0 disables (default); intended to be
    // set HIGH so only extreme outliers are touched and the normal image is
    // unchanged.
    void setSplatLuminanceClamp(double clamp);

    // Total number of hits this worker is holding in its claim-output-first
    // overflow buffers (work that is enqueued nowhere yet but not dropped).
    // The Renderer must include this in its drain-completion test, otherwise it
    // could observe all queues empty while a worker still holds parked hits and
    // stop the pipeline before that work is splatted. Reads plain size_t members
    // updated only by this worker's own thread; a stale read just keeps the
    // drain loop spinning one more 250ms tick, which is harmless.
    size_t pendingOverflow() const;

    std::shared_ptr<Camera> camera;
    std::vector<std::shared_ptr<Object>> objects;
    std::shared_ptr<LightQueue> lightQueue;
    std::shared_ptr<WorkQueue<Photon>> photonQueue;
    std::shared_ptr<WorkQueue<PhotonHit>> hitQueue;
    std::shared_ptr<WorkQueue<PhotonHit>> finalHitQueue;
    // EmitterQueue holds compact daughter-photon PRODUCERS (Wave 3) awaiting lazy
    // fan-out. processPhotons pushes one Emitter per bounceable hit here, in
    // parallel with the full-hit push to hitQueue. processEmissions pulls an
    // emitter back, RESERVES photon-queue space first (claim-output-first), and
    // generates only as many daughters as fit, requeuing the emitter while it
    // still has daughters left. This replaces Wave 2's eager all-N fan-out: the
    // photon queue no longer needs N contiguous slots per hit, and this queue
    // stores a compact producer instead of N-multiplied PhotonHits.
    std::shared_ptr<EmitterQueue> emitterQueue;
    std::shared_ptr<MaterialLibrary> materialLibrary;
    std::shared_ptr<Buffer> buffer;
    std::shared_ptr<Image> image;
    // Storage pivot: the QUANTIZED DENSITY GRID. Each non-delta photon bounce is
    // accumulated into the grid CELL it lands in (add(position, power)) instead of
    // stored as a per-photon record. Bounded by occupied cells, not photon count.
    // The mirror gather looks this up at reflected surface points after the pass.
    // May be null (then grid accumulation is skipped).
    std::shared_ptr<DensityGrid> densityGrid;
    // Continuous-time transform oracle (vision doc pillar 1). Default initialization is
    // a StaticAnimationQuery — every transformAt() call returns the scene-load transform
    // regardless of time. Workers currently read object positions through the existing
    // Object::position() path; the animation query is plumbed for future use without
    // requiring a Worker API change.
    std::shared_ptr<AnimationQuery> animationQuery;

    size_t emitDuration = 0;
    size_t photonDuration = 0;
    size_t hitDuration = 0;
    size_t writeDuration = 0;

    size_t emitProcessed = 0;
    size_t photonsProcessed = 0;
    size_t hitsProcessed = 0;
    size_t finalHitsProcessed = 0;

private:
    bool processLights();
    bool processPhotons();
    bool processEmissions();

    // Storage pivot M2: restored DIRECT CAMERA SPLAT. When a photon hits a
    // NON-DELTA surface, project the hit into camera pixel space; if it is
    // in-frustum, the surface faces the camera, and nothing occludes the line of
    // sight, accumulate the bounce's outgoing radiance toward the camera into that
    // pixel's buffer, then discard the photon. This is the cheap
    // "camera-consumes-the-bounce" model — no per-photon storage — and it gives
    // SHARP direct/diffuse visibility (each photon lands in its exact projected
    // pixel, not smeared over a gather radius).
    //
    // The accumulated value matches the gather's physical-luminance normalization
    // so the existing tonemap is unchanged: each photon contributes
    //   BRDF(wi -> toCamera) * power / (N * pi * r^2)
    // where r = cameraDistance * tan(pixelHalfAngle) is the pixel's world-space
    // footprint radius at the hit depth (same footprint the gather computes), and
    // N = photonsPerLight. Summed over all photons landing in a pixel's footprint
    // this equals the gather's invN/(pi r^2) * sum(BRDF*power) estimate.
    void splatToCamera(const PhotonHit& photonHit, const std::shared_ptr<Material>& material);

public:
    // Storage pivot M3 (multi-camera): a camera the splat targets, paired with the
    // buffer it accumulates into and that camera's debug-deposit filters. The
    // worker splats every camera-visible non-delta bounce into EVERY target whose
    // frustum/filters admit it, so multi-camera and debug cameras (bounce/light
    // filters) keep working under the splat model — each camera's direct image is
    // produced in the photon pass instead of by a per-photon gather.
    struct SplatTarget
    {
        std::shared_ptr<Camera> camera;
        std::shared_ptr<Buffer> buffer;
        int bounceFilter = -1;  // -1 = admit all bounce depths
        int lightFilter = -1;   // -1 = admit all light ids
    };
    void setSplatTargets(const std::vector<SplatTarget>& targets);

private:
    // Wave 4b: processHits (camera-visibility) and processFinalHits (the splat
    // sink) were removed with the forward splat. The image is now produced by the
    // gather over the deposit cloud (src/Gather.cpp), run after the photon pass.

    // Claim-output-first helper. Push as many of `items` into `queue` as the
    // queue's clamped allocation allows; whatever does not fit stays in `items`
    // (erased-from-front for what was placed). Returns true if the buffer was
    // fully drained. Used to make every producer site lossless: a stage holds
    // its un-enqueued output in a persistent per-worker overflow buffer and
    // retries on a later iteration instead of dropping.
    //
    // Templated over the element type so the same lossless-flush logic serves
    // both the PhotonHit paths (hit / final-hit overflow) and the Emitter path
    // (emitter overflow).
    template <typename T>
    bool flushIntoQueue(std::vector<T>& items, WorkQueue<T>& queue)
    {
        if (items.empty())
        {
            return true;
        }

        // initialize() clamps to the queue's remaining capacity, so the returned
        // block tells us exactly how many items the queue can accept right now.
        auto block = queue.initialize(items.size());
        const size_t placed = block.size();

        for (size_t i = 0; i < placed; ++i)
        {
            block[i] = items[i];
        }
        queue.ready(block);

        if (placed == items.size())
        {
            items.clear();
            return true;
        }

        // Partial placement: keep the unplaced tail for a later iteration. Nothing
        // is dropped — this is the back-pressure hold.
        items.erase(items.begin(), items.begin() + placed);
        return false;
    }

    size_t m_index = 0;
    size_t m_fetchSize = 0;

    // Hard safety CAP on bounce depth (decay is the real terminator). Kept large
    // by config so a near-unity-albedo path cannot loop forever.
    size_t m_bounceThreshold = 1;

    // Single-photon decay-termination ABSOLUTE floor (see setTerminationThreshold).
    double m_terminationThreshold = 1.0;

    RussianRouletteConfig m_russianRoulette;

    size_t m_daughterCountOverride = 0;
    double m_daughterCountScale = 1.0;

    // Storage pivot M2: photons-per-light N for the direct splat's 1/N divide.
    // 0 disables the splat (no normalization possible).
    double m_photonsPerLight = 0.0;

    // Firefly fix: world-space minimum splat-footprint radius (see setter doc).
    // 0 disables the floor.
    double m_minSplatRadius = 0.0;

    // Optional extreme-firefly guard: per-splat luminance clamp (see setter doc).
    // <= 0 disables (default).
    double m_splatLuminanceClamp = 0.0;

    // Storage pivot M3: the cameras + buffers the splat accumulates into (one per
    // scene camera). Set by the Renderer before the worker starts.
    std::vector<SplatTarget> m_splatTargets;

    // Resolve the daughter count for a bounceable hit, applying the override /
    // scale config on top of the material's native daughterPhotonCount().
    size_t resolveDaughterCount(size_t materialCount) const;

    std::thread m_thread;

    std::atomic_bool m_running;
    std::atomic_bool m_suspend;

    RandomGenerator m_generator;

    std::vector<Hit> m_castBuffer;
    std::vector<PhotonHit> m_hitBuffer;
    std::vector<PhotonHit> m_volumeHitBuffer;

    // Persistent per-worker overflow buffer (claim-output-first back-pressure).
    // When the emitter queue cannot accept a batch's full output, the surplus is
    // parked here and flushed on a later iteration — never dropped. processPhotons
    // refuses to fetch new source photons while this overflow is non-empty, which
    // bounds it to at most one batch worth of emitters.
    //   - m_emitterOverflow: compact Emitters awaiting the EmitterQueue (daughter path)
    // Wave 4b: the splat-path overflow buffers (m_hitOverflow, m_finalOverflow)
    // were removed with the forward splat.
    std::vector<Emitter> m_emitterOverflow;

    // Cross-thread-visible mirror of the overflow buffer size above.
    // Written only by this worker's thread (after every mutation via
    // syncOverflowGauge), read by the Renderer drain loop. Atomic so the read
    // is well-defined; relaxed ordering is fine since it's only a liveness hint.
    std::atomic<size_t> m_pendingOverflowGauge{0};
    void syncOverflowGauge();

    std::exception_ptr m_exception;
};

// Diagnostic counters for the delta-material cone gate in processFinalHits. Reset between
// frames; queried after the render completes. Will be removed once the cone-budget tuning
// settles.
namespace WorkerDebug
{
size_t deltaHitsTotal();
size_t deltaHitsAccepted();
size_t deltaHitsRejectedBackface();
size_t deltaHitsRejectedConeOffset();
void resetDeltaHitCounters();

// Firefly-fix splat counters: total splat contributions vs those whose
// footprint radius was floored to the minimum-radius (the would-be fireflies).
size_t splatTotal();
size_t splatRadiusClamped();
// Optional luminance-clamp guard: splats whose contributed luminance exceeded
// the per-splat clamp and were scaled down. 0 when the clamp is disabled.
size_t splatLuminanceClamped();
void resetSplatCounters();

// Drop counters: number of pipeline items discarded because a destination
// WorkQueue was full. Queried after the render drains. Must be zero once
// claim-output-first back-pressure is in place.
size_t droppedEmitting();
size_t droppedRequeue();
size_t droppedHit();
size_t droppedFinal();
size_t droppedTotal();
void resetDropCounters();
}
