#pragma once

#include "AnimationQuery.h"
#include "BounceCloud.h"
#include "Buffer.h"
#include "Camera.h"
#include "Emitter.h"
#include "EmitterQueue.h"
#include "Hit.h"
#include "Image.h"
#include "LightQueue.h"
#include "Material.h"
#include "MaterialLibrary.h"
#include "Object.h"
#include "Photon.h"
#include "RandomGenerator.h"
#include "Volume.h"
#include "WorkQueue.h"

#include <atomic>
#include <exception>
#include <memory>
#include <thread>
#include <vector>

/*

Pipeline: Photons <-> Hits -> Final hits -> Write

Photons:
* Emitted / bounced photons to cast against the scene
* Generated by lights and emissive volumes at the beginning of a frame
* Generated at bounce sites depending on material properties and number of bounces allowed

Hits:
* Results of photon casts from the previous queue
* Depending on material properties and remaining bounces, will emit more photons to be calculated
* If visible to the camera (normal facing camera, no objects between hit and camera), added to the final hits queue

Final hits:
* Scanned by "pixel sensors" to be written to final image

If photons are available, process those
Else if hits are available, process those
Else if final hits are available, scan those into the image buffer
Else, sleep

*/

class Worker
{
public:
    Worker(size_t index, size_t fetchSize);

    void start();
    void suspend();
    void resume();
    void stop();
    void exec();
    std::exception_ptr exception();

    void setBounceThreshold(size_t bounceThreshold);

    // Total number of hits this worker is holding in its claim-output-first
    // overflow buffers (work that is enqueued nowhere yet but not dropped).
    // The Renderer must include this in its drain-completion test, otherwise it
    // could observe all queues empty while a worker still holds parked hits and
    // stop the pipeline before that work is splatted. Reads plain size_t members
    // updated only by this worker's own thread; a stale read just keeps the
    // drain loop spinning one more 250ms tick, which is harmless.
    size_t pendingOverflow() const;

    std::shared_ptr<Camera> camera;
    std::vector<std::shared_ptr<Object>> objects;
    std::shared_ptr<LightQueue> lightQueue;
    std::shared_ptr<WorkQueue<Photon>> photonQueue;
    std::shared_ptr<WorkQueue<PhotonHit>> hitQueue;
    std::shared_ptr<WorkQueue<PhotonHit>> finalHitQueue;
    // EmitterQueue holds compact daughter-photon PRODUCERS (Wave 3) awaiting lazy
    // fan-out. processPhotons pushes one Emitter per bounceable hit here, in
    // parallel with the full-hit push to hitQueue. processEmissions pulls an
    // emitter back, RESERVES photon-queue space first (claim-output-first), and
    // generates only as many daughters as fit, requeuing the emitter while it
    // still has daughters left. This replaces Wave 2's eager all-N fan-out: the
    // photon queue no longer needs N contiguous slots per hit, and this queue
    // stores a compact producer instead of N-multiplied PhotonHits.
    std::shared_ptr<EmitterQueue> emitterQueue;
    std::shared_ptr<MaterialLibrary> materialLibrary;
    std::shared_ptr<Buffer> buffer;
    std::shared_ptr<Image> image;
    // Wave 4a: persistent append-only deposit store. When a photon hits a
    // NON-DELTA surface (Lambertian / Microfacet — not a pure Mirror), the
    // worker appends one BounceRecord here in parallel with the existing forward
    // splat. The deposit is a lock-free atomic fetch-add append, so it does not
    // serialize the workers. Built/queried only after the pass drains (Wave 4b
    // gather). May be null — when unset, deposits are skipped and the pipeline
    // behaves exactly as Wave 3 (the splat is unaffected either way).
    std::shared_ptr<BounceCloud> bounceCloud;
    // Continuous-time transform oracle (vision doc pillar 1). Default initialization is
    // a StaticAnimationQuery — every transformAt() call returns the scene-load transform
    // regardless of time. Workers currently read object positions through the existing
    // Object::position() path; the animation query is plumbed for future use without
    // requiring a Worker API change.
    std::shared_ptr<AnimationQuery> animationQuery;

    size_t emitDuration = 0;
    size_t photonDuration = 0;
    size_t hitDuration = 0;
    size_t writeDuration = 0;

    size_t emitProcessed = 0;
    size_t photonsProcessed = 0;
    size_t hitsProcessed = 0;
    size_t finalHitsProcessed = 0;

private:
    bool processLights();
    bool processPhotons();
    bool processEmissions();
    bool processHits();
    bool processFinalHits();

    // Claim-output-first helper. Push as many of `items` into `queue` as the
    // queue's clamped allocation allows; whatever does not fit stays in `items`
    // (erased-from-front for what was placed). Returns true if the buffer was
    // fully drained. Used to make every producer site lossless: a stage holds
    // its un-enqueued output in a persistent per-worker overflow buffer and
    // retries on a later iteration instead of dropping.
    //
    // Templated over the element type so the same lossless-flush logic serves
    // both the PhotonHit paths (hit / final-hit overflow) and the Emitter path
    // (emitter overflow).
    template <typename T>
    bool flushIntoQueue(std::vector<T>& items, WorkQueue<T>& queue)
    {
        if (items.empty())
        {
            return true;
        }

        // initialize() clamps to the queue's remaining capacity, so the returned
        // block tells us exactly how many items the queue can accept right now.
        auto block = queue.initialize(items.size());
        const size_t placed = block.size();

        for (size_t i = 0; i < placed; ++i)
        {
            block[i] = items[i];
        }
        queue.ready(block);

        if (placed == items.size())
        {
            items.clear();
            return true;
        }

        // Partial placement: keep the unplaced tail for a later iteration. Nothing
        // is dropped — this is the back-pressure hold.
        items.erase(items.begin(), items.begin() + placed);
        return false;
    }

    size_t m_index = 0;
    size_t m_fetchSize = 0;

    size_t m_bounceThreshold = 1;

    std::thread m_thread;

    std::atomic_bool m_running;
    std::atomic_bool m_suspend;

    RandomGenerator m_generator;

    std::vector<Hit> m_castBuffer;
    std::vector<PhotonHit> m_hitBuffer;
    std::vector<PhotonHit> m_volumeHitBuffer;

    // Persistent per-worker overflow buffers (claim-output-first back-pressure).
    // When a producer queue cannot accept a batch's full output, the surplus is
    // parked here and flushed on a later iteration — never dropped. processPhotons
    // refuses to fetch new source photons while either of its overflows is
    // non-empty, which bounds these to at most one batch worth of hits.
    //   - m_hitOverflow:     bounce-hits awaiting the hitQueue (splat path)
    //   - m_emitterOverflow: compact Emitters awaiting the EmitterQueue (daughter path)
    //   - m_finalOverflow:   camera-visible hits awaiting the finalHitQueue
    std::vector<PhotonHit> m_hitOverflow;
    std::vector<Emitter> m_emitterOverflow;
    std::vector<PhotonHit> m_finalOverflow;

    // Cross-thread-visible mirror of the three overflow buffer sizes above.
    // Written only by this worker's thread (after every mutation via
    // syncOverflowGauge), read by the Renderer drain loop. Atomic so the read
    // is well-defined; relaxed ordering is fine since it's only a liveness hint.
    std::atomic<size_t> m_pendingOverflowGauge{0};
    void syncOverflowGauge();

    std::exception_ptr m_exception;
};

// Diagnostic counters for the delta-material cone gate in processFinalHits. Reset between
// frames; queried after the render completes. Will be removed once the cone-budget tuning
// settles.
namespace WorkerDebug
{
size_t deltaHitsTotal();
size_t deltaHitsAccepted();
size_t deltaHitsRejectedBackface();
size_t deltaHitsRejectedConeOffset();
void resetDeltaHitCounters();

// Drop counters: number of pipeline items discarded because a destination
// WorkQueue was full. Queried after the render drains. Must be zero once
// claim-output-first back-pressure is in place.
size_t droppedEmitting();
size_t droppedRequeue();
size_t droppedHit();
size_t droppedFinal();
size_t droppedTotal();
void resetDropCounters();
}
